# Generated by Django 4.0.3 on 2022-03-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
